apiVersion: apps/v1
kind: Deployment
metadata:
  name: fresh-milk-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fresh-milk
  template:
    metadata:
      labels:
        app: fresh-milk
    spec:
      containers:
      - name: fresh-milk-container
        image: us-central1-docker.pkg.dev/web-application-deploy-489908/my-repo/fresh-milk-app:v1
        ports:
        - containerPort: 5000
