apiVersion: apps/v1
kind: Deployment
metadata:
  name: fresh-milk-app
spec:
  replicas: 3   # High availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fresh-milk
  template:
    metadata:
      labels:
        app: fresh-milk
    spec:
      containers:
      - name: fresh-milk-container
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20