apiVersion: apps/v1
kind: Deployment
metadata:
  name: fresh-milk-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: fresh-milk
  template:
    metadata:
      labels:
        app: fresh-milk
    spec:
      containers:
      - name: fresh-milk-container
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
