apiVersion: apps/v1
kind: Deployment
metadata:
  name: fresh-milk-app
spec:
  replicas: 1   # ✅ reduce for 1 node

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: fresh-milk-app

  template:
    metadata:
      labels:
        app: fresh-milk-app

    spec:
      containers:
        - name: milk-container
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 5000

          # ✅ SIMPLE ENV (no MySQL for now)
          env:
            - name: DB_URL
              value: "sqlite:///milk.db"
            - name: SECRET_KEY
              value: "test123"

          # ✅ LOW RESOURCE (IMPORTANT)
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"