apiVersion: v1
kind: Secret
metadata:
  name: milk-secret
type: Opaque
data:
  DB_USER: bXl1c2Vy        # base64(myuser)
  DB_PASSWORD: bXlwYXNz    # base64(mypass)
  SECRET_KEY: c3VwZXJzZWNyZXQ=  # base64(supersecret)