apiVersion: v1
kind: Service
metadata:
  name: fresh-milk-service
spec:
  type: LoadBalancer
  selector:
    app: fresh-milk-app   # ✅ must match deployment label
  ports:
    - port: 80
      targetPort: 5000